-- MySQL Script generated by MySQL Workbench
-- Thu May 18 14:28:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_captain
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_captain` ;

-- -----------------------------------------------------
-- Schema db_captain
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_captain` DEFAULT CHARACTER SET utf8 ;
USE `db_captain` ;

-- -----------------------------------------------------
-- Table `db_captain`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Players` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Players` (
  `idPlayer` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `player_pwd` VARCHAR(150) NULL,
  `email` VARCHAR(150) NULL,
  `num_keys` INT NULL,
  `stamps` INT NULL,
  `lastLogin` DATETIME NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  `privileges` SMALLINT(2) NULL DEFAULT 0,
  PRIMARY KEY (`idPlayer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Top`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Top` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Top` (
  `idTop` INT NOT NULL AUTO_INCREMENT,
  `top_style` VARCHAR(45) NULL,
  `top_color` VARCHAR(45) NULL,
  PRIMARY KEY (`idTop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Skin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Skin` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Skin` (
  `idSkin` INT NOT NULL AUTO_INCREMENT,
  `skin_color` VARCHAR(45) NULL,
  PRIMARY KEY (`idSkin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Bottom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Bottom` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Bottom` (
  `idBottom` INT NOT NULL AUTO_INCREMENT,
  `bottom_style` VARCHAR(45) NULL,
  `bottom_color` VARCHAR(45) NULL,
  PRIMARY KEY (`idBottom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Accessory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Accessory` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Accessory` (
  `idAccessory` INT NOT NULL AUTO_INCREMENT,
  `accessory_style` VARCHAR(45) NULL,
  PRIMARY KEY (`idAccessory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Hair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Hair` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Hair` (
  `idHair` INT NOT NULL AUTO_INCREMENT,
  `hair_style` VARCHAR(45) NULL,
  `hair_color` VARCHAR(45) NULL,
  PRIMARY KEY (`idHair`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Avatar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Avatar` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Avatar` (
  `idAvatar` INT NOT NULL AUTO_INCREMENT,
  `Players_idPlayer` INT NOT NULL,
  `genre` VARCHAR(5) NULL,
  `Top_idTop` INT NOT NULL,
  `Skin_idSkin` INT NOT NULL,
  `Bottom_idBottom` INT NOT NULL,
  `Accessory_idAccessory` INT NOT NULL,
  `Hair_idHair` INT NOT NULL,
  PRIMARY KEY (`idAvatar`, `Players_idPlayer`, `Top_idTop`, `Skin_idSkin`, `Bottom_idBottom`, `Accessory_idAccessory`, `Hair_idHair`),
  INDEX `fk_Avatar_Players_idx` (`Players_idPlayer` ASC),
  INDEX `fk_Avatar_Top1_idx` (`Top_idTop` ASC),
  INDEX `fk_Avatar_Skin1_idx` (`Skin_idSkin` ASC),
  INDEX `fk_Avatar_Bottom1_idx` (`Bottom_idBottom` ASC),
  INDEX `fk_Avatar_Accessory1_idx` (`Accessory_idAccessory` ASC),
  INDEX `fk_Avatar_Hair1_idx` (`Hair_idHair` ASC),
  CONSTRAINT `fk_Avatar_Players`
    FOREIGN KEY (`Players_idPlayer`)
    REFERENCES `db_captain`.`Players` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avatar_Top1`
    FOREIGN KEY (`Top_idTop`)
    REFERENCES `db_captain`.`Top` (`idTop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avatar_Skin1`
    FOREIGN KEY (`Skin_idSkin`)
    REFERENCES `db_captain`.`Skin` (`idSkin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avatar_Bottom1`
    FOREIGN KEY (`Bottom_idBottom`)
    REFERENCES `db_captain`.`Bottom` (`idBottom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avatar_Accessory1`
    FOREIGN KEY (`Accessory_idAccessory`)
    REFERENCES `db_captain`.`Accessory` (`idAccessory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avatar_Hair1`
    FOREIGN KEY (`Hair_idHair`)
    REFERENCES `db_captain`.`Hair` (`idHair`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Planets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Planets` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Planets` (
  `idPlanet` INT NOT NULL AUTO_INCREMENT,
  `Planet_name` VARCHAR(100) NULL,
  PRIMARY KEY (`idPlanet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Questions` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Questions` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `Question` VARCHAR(250) NULL,
  PRIMARY KEY (`idQuestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Levels` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Levels` (
  `idLevel` INT NOT NULL AUTO_INCREMENT,
  `idPlanet` INT NOT NULL,
  `idQuestion` INT NOT NULL,
  PRIMARY KEY (`idLevel`, `idPlanet`, `idQuestion`),
  INDEX `fk_Levels_Planets1_idx` (`idPlanet` ASC),
  INDEX `fk_Levels_Questions1_idx` (`idQuestion` ASC),
  CONSTRAINT `fk_Levels_Planets1`
    FOREIGN KEY (`idPlanet`)
    REFERENCES `db_captain`.`Planets` (`idPlanet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Levels_Questions1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `db_captain`.`Questions` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Game` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Game` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `lastLevelPlayed` INT NOT NULL,
  `game_start` DATETIME NULL,
  `game_end` DATETIME NULL,
  `wins` INT NULL,
  `loses` INT NULL,
  PRIMARY KEY (`idGame`, `idPlayer`, `lastLevelPlayed`),
  INDEX `fk_Game_Players1_idx` (`idPlayer` ASC),
  INDEX `fk_Game_Levels1_idx` (`lastLevelPlayed` ASC),
  CONSTRAINT `fk_Game_Players1`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `db_captain`.`Players` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_Levels1`
    FOREIGN KEY (`lastLevelPlayed`)
    REFERENCES `db_captain`.`Levels` (`idLevel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_captain`.`Answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_captain`.`Answers` ;

CREATE TABLE IF NOT EXISTS `db_captain`.`Answers` (
  `idAnswer` INT NOT NULL AUTO_INCREMENT,
  `idQuestion` INT NOT NULL,
  `answer` VARCHAR(250) NULL,
  `correct` INT NULL,
  PRIMARY KEY (`idAnswer`, `idQuestion`),
  INDEX `fk_Answers_Questions1_idx` (`idQuestion` ASC),
  CONSTRAINT `fk_Answers_Questions1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `db_captain`.`Questions` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
